server:
  port: 80

spring:
  application:
    name: cloud-consumer-hystrix-order

#这里只把feign做客户端用，不注册进eureka
eureka:
  instance:
    instance-id: order80
    prefer-ip-address: true #访问路径可以显示IP地址
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/ #单机版

#设置feign客户端超时时间（OpenFeign默认支持ribbon）
 #ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的实际
   #ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
   #ConnectTimeout: 5000

#这里只把feign做客户端用，不注册进eureka
feign:
  hystrix:
    enabled: true